language: generic
sudo: required

services:
  - docker

#series of different command before our test runs
before_install:
  - docker build -t punss21/docker-react -f Dockerfile.dev .

#series of command which needs tob e run for tests
script:
  - docker run -e CI=true punss21/docker-react npm run test -- --coverage